#define SEQUENCER_TRACKS_NUM 8
#define SEQUENCER_EIGHTH_NOTE_NUM 32
#define SEQUENCER_MEASURES_NUM 4
#define SEQUENCER_EIGHTH_NOTE_BY_MEASURE_NUM 8
#define SEQUENCER_MARBLE_BY_MEASURE_NUM (SEQUENCER_EIGHTH_NOTE_BY_MEASURE_NUM * SEQUENCER_TRACKS_NUM)
#define SEQUENCER_PAGES_NUM 8