#include "BeatsLEDSnake.h"

BeatsLEDSnake::BeatsLEDSnake() : LEDArray(BEATS_SNAKE_NUM_LEDS, BEATS_SNAKE_LED_POWER_PIN, BEATS_SNAKE_MUX_S0_PIN, BEATS_SNAKE_MUX_S1_PIN, BEATS_SNAKE_MUX_S2_PIN, BEATS_SNAKE_MUX_S3_PIN)
{
}